server:
  port: 9053

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  application:
    name: mall-ease-user

  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

url:
  path: mall-ease-admin

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

redis:
  database: mall-swarm
  key:
    admin: 'ums:admin'
  expire:
    common: 86400

sa-token:
  token-name: Authorization
  timeout: 604800
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
  is-read-cookie: false
  is-read-header: true
  token-prefix: Bearer
  jwt-secret-key: ${SA_TOKEN_SECRET:sa-secret-key-default}
  is-print: false
